# Generated by Django 5.1.6 on 2025-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default-img.jpg', upload_to='images/%d/%m/%y'),
        ),
    ]
