# Generated by Django 5.1.6 on 2025-03-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_time',
            new_name='cook_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
