# Generated by Django 5.1.6 on 2025-02-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
