# Generated by Django 5.1.6 on 2025-03-02 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_cooking_time_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='calories_per_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(default='', max_length=64)),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.ingredient')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='app.recipeingredient'),
        ),
    ]
