# Generated by Django 5.1.6 on 2025-03-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipe_cooking_time_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtype',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='mealtype',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
