# Generated by Django 5.1.6 on 2025-03-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_mealtype_meal_type_mealtype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='value',
            new_name='name',
        ),
    ]
