# Generated by Django 5.1.6 on 2025-03-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, upload_to='images/%d/%m/%y'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ratings',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipes', to='app.rating'),
        ),
    ]
