# Generated by Django 5.1.6 on 2025-03-02 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_ingredient_calories_per_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='name',
            new_name='ingredient',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='app.recipe'),
        ),
    ]
