# Generated by Django 5.1.6 on 2025-03-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_recipe_image_alter_recipe_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='app.rating'),
        ),
    ]
