# Generated by Django 5.1.6 on 2025-02-15 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_recipe_rating_rating_user_recipe_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.recipe'),
        ),
    ]
